language: cpp
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get -y install build-essential # autotools-dev automake autoconf

  - sudo apt-get install -y libbz2-dev
  - sudo apt-get install -y libsmpeg-dev
  - sudo apt-get install -y libfreetype6-dev
  - sudo apt-get install -y libnotify-dev

  - mkdir travis_build_deps
  - cd travis_build_deps

  - wget https://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - tar xvf SDL2-2.0.3.tar.gz
  - cd SDL2-2.0.3
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..

  - wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz
  - tar xvf SDL2_image-2.0.0.tar.gz
  - cd SDL2_image-2.0.0
  - ./configure
  - make
  - sudo make install
  - cd ..

  - wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.0.tar.gz
  - tar xvf SDL2_mixer-2.0.0.tar.gz
  - cd SDL2_mixer-2.0.0
  - ./configure
  - make
  - sudo make install
  - cd ..

  - cd ..
script:
  - ./configure --unsupported-compiler
  - make
# notifications:
#   irc:
#     channels:
#       - "irc.rizon.net#vnengine"
#     template:
#       - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"