language: cpp
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get -y install build-essential # autotools-dev automake autoconf

  - mkdir deps
  - cd deps

  - cd ../../../
  - wget https://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - tar xvf SDL2-2.0.3.tar.gz
  - cd SDL2-2.0.3
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install

  - cd ../../
  - wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz
  - tar xvf SDL2_image-2.0.0.tar.gz
  - cd SDL2_image-2.0.0
  - ./configure
  - make
  - sudo make install

  - cd ~
  - mkdir build
  - cd build

  - sudo apt-get install -y libsdl2-mixer-dev
  - sudo apt-get install -y libbz2-dev
  - sudo apt-get install -y libsmpeg-dev
  - sudo apt-get install -y libfreetype6-dev
  - sudo apt-get install -y libnotify-dev
script:
  - which aclocal
  - aclocal --version
  - which aclocal-1.13
  - ./configure --unsupported-compiler
  # - make
# notifications:
#   irc:
#     channels:
#       - "irc.rizon.net#vnengine"
#     template:
#       - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"